### ISSUE TITLE
Implement model and ProjectController

### ISSUE THREAD

**Issue by ImanuelRichter** [ImanuelRichter/ARdevKit#1]

**Comment by RockItDown** [comment]
got a question about consistency:

1.)private param
   public Param
   { get{return param;}
     set{param = value;}
   }

or

public param { get;set;}

which to prefer, because their is both in some classes, and then a naming issue:

augmentations or augmentions

according to the draft it is augmentations, but gramatically its wrong.
should I use obsolete when its changed, because this would lead to more confusing code

**Comment by Lizzard2397** [comment]
to the first question:
it's the same the first is the long version, ne second is the short version!

and i think augmentations!? but don't know which the correct form is.
when you change this you should have a lot of fun :D i've used this many times :D

**Comment by RockItDown** [comment]
i know that these to forms are equivalent, but which one to use, for readability.
i think i stick with the longer one, because it is more accurate when it comes to the draft.

**Comment by Lizzard2397** [comment]
i think the short form is better and is better to read... but tell this Marwin xD he implements all in the long version

**Comment by ImanuelRichter** [comment]
1. Now i prefer the long version, too, because you can define primitive types instant
2. I think augmentions is right so lets use that one^^

**Comment by RockItDown** [comment]
ok, i will change every Augmentation to Augmention, the draft must be corrected in the same way

**Comment by Bareus** [comment]
Just want to ask: who had implemented the class DbSource? In this class is an variable of type DbConnection, which is a Controller class o.O 
Was this intended or just a mistake, because, if I recall correctly, the model should not know about the controller, right?

**Comment by geht** [comment]
closed, reopen if something's missing or if relevant
