### ISSUE TITLE
Milestone custom user events including templates due

### ISSUE THREAD

**Issue by geht** [ImanuelRichter/ARdevKit#106]
Milestone custom user events including templates is due to 14.02.2014 20:00 UTC + 01:00

**Comment by Bareus** [comment]
implemented basic editor in d06c907689. 
you can edit stuff, but it doesn't load a template by default. i'm stil trying to figure out, how to do it...

**Comment by Bareus** [comment]
fully implemented textEditor in 3115bab3d1
you can save and close the editor (no dialog, if you want to save, if you havenv't done yet)
it loads the customUserEventTemplate by default from res/templates in the /debug/ folder.

still not closed, because i want to seperate all properties which should be edited by the TextEditor from the propertyGrid

**Comment by Bareus** [comment]
oke, i added a constructor to the TextEditorForm in b1c987a83e . Now you can load any .txt file, if a file path has been forwarded in the constructor. I still haven't seperated all properties (sources, customUserEvent etc.) from the propertyGrid, but I need some help by this, since I must either change some parts in the EditorWindow or somebody helps me including a "Bearbeite AREL Script" to the context menu or we make both... .

I also need to change the menu "Öffne SourceFile" such that it will open my editor instead of the std editor of windows.

Edit: Oh yeah I forgot - I need some kind of template for the sourceFile and query etc. Also I wanted to know: Should the initial templates from us be accessible for the user, or not? Because right now they are accessible....

**Comment by geht** [comment]
IMHO we should leave the entry in the property panel as it is now. I think it is more elegant to be able to open the editor via the property panel than via an extra button...
Furthermore I think there should be an addition to the context menu of the augmentations like "Lade UserEventDatei" which opens a file dialog where you can select a file and load it into the editor

**Comment by Bareus** [comment]
ok, I think I can close this issue, since I have made some new issues which specify exactly what is still missing.

Btw: Sry, that it goes over the deadline >.< Hope it is not too inconvenient because of my slowness....

**Comment by geht** [comment]
i see that there are still open issues directed to others.
If those functions you added are stable and compilable I would like you to merge to the master please.
