### ISSUE TITLE
Implement classes from model

### ISSUE THREAD

**Issue by ImanuelRichter** [ImanuelRichter/ARdevKit#11]

**Comment by RockItDown** [comment]
In Order to show a visual reprantasation, this representation has to be drawn first. In order to make this possible, I have to provide pictures, which functions at least as a template for the actual representation. I need a place to Store these, where should they go?

**Comment by Bareus** [comment]
What do you mean with visual represantation? Like the elements, which are shown in the ElementSelectionPanel, or like stub version of an element in the PreviewPanel?

Anyway, if you need a place to store pictures, create a new folder in the /Editor/ folder (e.g.: /Editor/Resource/). You should be able to make a relativ path to this folder, because it's still in the project folder.

**Comment by Lizzard2397** [comment]
i need in Abstract Trackable a get(), add(), remove(), isFull() and a find() method, which returns the index of the element in this array, method for the array of Subobjects and in AbstractSource a method for set and get the Subsource! ty!
also you must implement all getter and setter of such model classes!

**Comment by Lizzard2397** [comment]
done by myself comes with next commit in branch PreviewController!

**Comment by Lizzard2397** [comment]
cdad7335f710ec1eccfd6dff5ca09133b3ab66a8
merged all classes and stubs from Model in master
