### ISSUE TITLE
Implement methods and attributes in PropertyController

### ISSUE THREAD

**Issue by ImanuelRichter** [ImanuelRichter/ARdevKit#13]

**Comment by Bareus** [comment]
Our design pattern has some mistakes. The method "addCustomUserEvent() : File"  is in it's original form unimplementable. The class "File" is in C# a static class, so no instance can be created from it. Also, I need a reference to the content, which should be saved somewhere in the model. So I have changed it like this:

addCustomUserEvent(selectedElement : AbstractAugmentation , content : string[]) : void

Also the class AbstractAugmentation needs to be changed, becaus of the missing File class. In my branch I have created a private class CustomUserEvent with the attributes "name : string" and "content : string[]"

If anyone wants to have a close look, what I have done, I will push my branch.

Oh yeah, I also changed the other method "editCustomUserEvent(customUserEvent : File) " because of the same reasons. Here are my changes:

getCusomUserEvent(selectedElement : AbstractAugmentation , name : string) : string[]

**Comment by geht** [comment]
please take Issue #19 to heart (if you haven't already)

**Comment by Bareus** [comment]
Ok, I think I have implemented anything (except the updatePropertyPanel), which should be implemented for the PropertyController. I wait, until the model has been pushed, before I merge it with the master branch.
I will declare this issue #13 as closed and rewrite the other issue, that the implementation still needs to be merged with the master branch.
