### ISSUE TITLE
Implement ElementSelectionController and connected classes

### ISSUE THREAD

**Issue by ImanuelRichter** [ImanuelRichter/ARdevKit#2]

**Comment by cr0ssing** [comment]
implemented ElementSelectionController and pushed it to master. Adding elements is possible except sources -> needs adjustments in PreviewController

**Comment by Lizzard2397** [comment]
fucking crap! i can say the same thing to you as to Jonas!
Read the things we speak in skype an we wrote in github! 
ABSTRACTSOURCE IS NO PREVIEWABLE! Source is no object which we show in the previewPanel! it would only be add to the linked augmentation! 
the right method in previewController is there you musst only read my comments! addSOURCE!!!!!

**Comment by cr0ssing** [comment]
first: mind your FUCKING language! And we were not sure about that until today in TS. It's hard to remember everything we changed since designing, which was said in 10000 skype messages, if you can't be online 24/7. But thanks for your kind words :) The comments of addSource were not very helpful and the method was complete crap until I reworked it ;)

**Comment by cr0ssing** [comment]
finished ElementSelectionController. Elements can be chosen for categories and added by clicking and drap and drop. Sources are only dragged on existing Augmentations. TODO: Provide another cloning interface for proper recreating of object instances.

**Comment by cr0ssing** [comment]
implemented proper cloning interface.
